# -*- coding: utf-8 -*-
"""ADTarray

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nk6B3jU4bDwv_MrPQDLn4HSDFpBkOvKG
"""

"""
ADT Array.
"""
class Array():
  def __init__( self , tamano ):
    self.__tamano=tamano
    self.__data=[0 for x in range(self.__tamano)] #generator

  def get__item(self, index):
    return self.__data[index]

    def to__string( self ):
    print(self.__data)

ejemplo = Array (5)
ejemplo.to_string()
ejemplo.get_item(3)

"""# Nueva sección"""