# -*- coding: utf-8 -*-
"""contador .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBonVbNwXvDgfkO8qQJzfKtp6BxLRusj
"""

import time
numeros=[5,4,3,2,1,0]
for n in numeros:
  print(n)
  time.sleep(1)
  
print("!!BOOMM¡¡")