# -*- coding: utf-8 -*-
"""eliminar elementos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wqZSWHrLsBNO4mG_Y3FuLdLTcqQPhjL5
"""

lista =["hola", "a","todos"]
for x in range(len(lista)-1,-1,-1):
  if lista[x]=="a":
    print(lista.pop(x))
print(lista)